[package]
name = "raft-merkle"
version = "0.1.0"
edition = "2024"

[dependencies]
protobuf = "2.28.0"
raft = "0.7.0"
raft-proto = "0.7.0"
regex = "1.12.2"
slog = "2.8.2"
slog-async = "2.8.0"
slog-term = "2.9.2"
